### ISSUE TITLE
Broken (re)release of EDIM 1.3.7

### ISSUE THREAD

**Issue by fingolfin** [frankluebeck/EDIM#25]
You just (re)released EDIM 1.3.7. But actually that was already released in March 2023. The new version should have been 1.3.8.

Please restore the original EDIM 1.3.7 archives and then re-release this as 1.3.8.

**Comment by frankl-audio** [comment]
Oops, indeed. Sorry. Repacked it as version 1.3.8.

**Comment by frankluebeck** [comment]
Oops, indeed. Sorry. Repacked it as version 1.3.8.
